on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/postgresql@v1
      with:
        connection-string: ${{ secrets.DAEUNYIM_GH_FLEXIBLESERVERDB_POSTGRESQL_CONNECTION_STRING
          }}
        plsql-file: ./project-1/sql/products.sql
        server-name: daeunyim-gh.postgres.database.azure.com
